name = "my-project"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "<your-database-name>"
database_id = "<your-database-id>"

[[r2_buckets]]
binding = "AVATARS_BUCKET"
bucket_name = "<your-bucket-name>"

[vars]
BETTER_AUTH_URL = "http://localhost:8787"
