name = "imaimai-front-templete"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "imaimai-db"
database_id = "168111da-b164-46f3-aef0-7473b8d9846e"

[[r2_buckets]]
binding = "AVATARS_BUCKET"
bucket_name = "imaimai-avatars"

[vars]
BETTER_AUTH_URL = "http://localhost:8787"
